### ISSUE TITLE
pruning 오류 발생 : index out of bounds

### ISSUE THREAD

**Issue by heehehe** [heehehe/pruning-decorrelation#11]
pruning 정도 조절할 때 오류 발생

```
Traceback (most recent call last):
  File "modeling_pruning.py", line 113, in <module>
    main()
  File "modeling_pruning.py", line 92, in main
    criterion=criterion, optimizer=optimizer, device=device)
  File "/root/capstone/pruning-decorrelation/utils.py", line 218, in train
    filter_mask = get_filter_mask(model, prune['rate'])
  File "/root/capstone/pruning-decorrelation/utils.py", line 77, in get_filter_mask
    threshold = np.sort(importance_all)[int(len(importance_all) * rate)]
IndexError: index 2128 is out of bounds for axis 0 with size 2128
```

**Comment by heehehe** [comment]
pruning_rate를 1로 지정했을 때 발생한 문제
